import = ["~/.config/alacritty/dracula.toml"]

[font]
bold = {family = "MesloLGS NF", style = "Bold"}
italic = {family = "MesloLGS NF", style = "Italic"}
normal = {family = "MesloLGS NF", style = "Regular"}
size = 12

[window]
opacity = 0.8
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000
multiplier = 3

