[font]
bold = {family = "MesloLGS NF", style = "Bold"}
italic = {family = "MesloLGS NF", style = "Italic"}
normal = {family = "MesloLGS NF", style = "Regular"}
size = 12

[window]
opacity = 1.0

[scrolling]
history = 100000
multiplier = 3

[general]
import = ["~/.config/alacritty/dracula.toml"]

